name: Build and Deploy Docs

on:
  push:
    branches:
    - main
  pull_request:
    types: [opened,reopened,review_requested]
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: set git user
      run: |
        git config --global user.email "umsysteam@metoffice.gov.uk"
        git config --global user.name "SSD Developers"
    - name: Check out source
      uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install Sphinx packages
      run: |
         conda env create --file=env.yml 
         
    - name: build docs
      run: |
        conda activate sphinx_doc_env
        make clean html
        
    - name: commit docs to gh-pages branch
      if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      run: |
        git worktree add ../publish_wps
        cd ../publish_wps
        git fetch origin gh-pages 
        git checkout gh-pages
        cp -r ../simulation-systems/build/html/. .
        git add .
        git commit -am "Docs build"
        git push -u origin gh-pages
