name: Build and Deploy Docs

on:
  push:
    branches:
    - main
  pull_request:
    types: [opened,reopened,review_requested]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: set git user
      run: |
        git config --global user.email "umsysteam@metoffice.gov.uk"
        git config --global user.name "SSD Developers"
    - name: Check out source
      uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install Dependencies
      run: |
        pip install -r .github/workflows/requirements.txt

    - name: build docs
      run: |
        make clean html

    - name: commit docs to gh-pages branch
      if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      run: |
        git worktree add ../publish_wps
        cd ../publish_wps
        git fetch origin gh-pages
        git checkout gh-pages
        cp -r ../simulation-systems/build/html/. .
        git add .
        git commit -am "Docs build"
        git push -u origin gh-pages
