name: Build Docs

on:
  push:
    branches:
    - main
    - jennyhickson-patch-1
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675

    - run: |
         conda env create -f env.yml
         conda activate sphynx_doc_env
         make clean html
