name: Build Docs

on:
  push:
    branches:
    - main
    - jennyhickson-patch-1
    
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out source
      uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: |
         pip install Sphinx==4.5.0
         pip install sphinx-design==0.0.13
         pip install sphinx-rtd-theme==1.2.0
