name: Build Docs

on:
  push:
    branches:
    - main
    - jennyhickson-patch-1
    
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out source
      uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: |
         $CONDA/bin/conda env update -f env.yml --name base
         #conda activate sphynx_doc_env
         #make clean html
