name: Build Docs

on:
  push:
    branches:
    - main
    - jennyhickson-patch-1
    
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out source
      uses: actions/checkout@v3

    - run: |
         conda env create -f env.yml
         conda activate sphynx_doc_env
         make clean html
