# ------------------------------------------------------------------------------
# (c) Crown copyright Met Office. All rights reserved.
# The file LICENCE, distributed with this code, contains details of the terms
# under which the code may be used.
# ------------------------------------------------------------------------------

name: Docs

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    uses: MetOffice/growss/.github/workflows/sphinx-docs.yaml@develop
    with:
      python-version: "3.12.9"
      timeout-minutes: 10
      docs-dir: .
      source-dir: ./source
      use-pyproject: true

    permissions:
      contents: read
      pages: write
      id-token: write
